services:

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
  
volumes:
  sqlite_data: